### ISSUE TITLE
Handling of highres statusbars

### ISSUE THREAD

**Issue by NightFright2k19** [3saster/fullscrn_huds#8]
No idea whether it's doable, but apparently a mod called "Bloody Steel" uses a statusbar image with the dimensions of 1280x128. Obviously our mod has issues with it. 

Question is: Can we support it somehow without having to add tons of additional virtual textures cutting the graphics at the right places? Maybe there's a way to downscale everything to standard measures in advance.

Alternative: We declare our mod is not compatible with highres content.

**Comment by trzejos** [comment]
Not sure if it's related, but the statusbar graphics are also misaligned if using the unity widescreen statusbar for example

**Comment by NightFright2k19** [comment]
More or less fixed in v5.2.0, even though unsure if highscreen statusbars besides the Neural Upscale Pack should be supported.
